[project]
name = "summer3proto"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "David Shipman", email = "dshipman@gmail.com"}]
requires-python = ">= 3.11"
dependencies = [ "jax>=0.4.36,<0.5", "jaxlib>=0.4.36,<0.5", "numpy>=2.2.0,<2.3", "pandas>=2.2.3,<2.3", "numpyro>=0.16.1,<0.17", "blackjax>=1.2.4,<1.3", "diffrax>=0.6.0,<0.7", "jaxtyping>=0.2.36,<0.3", "typeguard>=2.13.3,<2.14"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
summer3proto = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
ipykernel = ">=6.29.5,<6.30"
matplotlib = ">=3.9.3,<3.10"
jupyter = ">=1.1.1,<1.2"
ipywidgets = ">=8.1.5,<8.2"
arviz = ">=0.20.0,<0.21"
plotly = ">=5.24.1,<5.25"
